services:
  db:
    container_name: my_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    restart: always
  app:
    container_name: my_app
    build: ./
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:admin@db/users
    command: bash -c 'while !<dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8000'
    ports:
      - "8000:8000"
    restart: always
